### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by Neodyn** [SK-CERT/Taranis-NG#108]
The command ( sudo TARANIS_NG_TAG=build docker compose -f docker/docker-compose.yml up --build) finished with:
```
 > [skcert/taranis-ng-gui:build build-stage 11/11] RUN npm run build:
#0 6.051
#0 6.051 > taranis-ng-ui@0.1.0 build
#0 6.051 > vue-cli-service build
#0 6.051
#0 12.19
#0 12.20 -  Building for production...
#0 20.39 Error: error:0308010C:digital envelope routines::unsupported
#0 20.39     at new Hash (node:internal/crypto/hash:71:19)
#0 20.39     at Object.createHash (node:crypto:133:10)
#0 20.39     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
#0 20.39     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
#0 20.39     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
#0 20.39     at /app/node_modules/webpack/lib/NormalModule.js:503:5
#0 20.39     at /app/node_modules/webpack/lib/NormalModule.js:358:12
#0 20.39     at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 20.39     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 20.39     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 20.39     at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 20.39     at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
#0 20.39     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
#0 20.39     at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
#0 20.39     at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
#0 20.39     at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
#0 25.15 /app/node_modules/loader-runner/lib/LoaderRunner.js:114
#0 25.15                        throw e;
#0 25.15                        ^
#0 25.15
#0 25.15 Error: error:0308010C:digital envelope routines::unsupported
#0 25.15     at new Hash (node:internal/crypto/hash:71:19)
#0 25.15     at Object.createHash (node:crypto:133:10)
#0 25.15     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
#0 25.15     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
#0 25.15     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
#0 25.15     at /app/node_modules/webpack/lib/NormalModule.js:503:5
#0 25.15     at /app/node_modules/webpack/lib/NormalModule.js:358:12
#0 25.15     at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 25.15     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 25.15     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 25.15     at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 25.15     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
#0 25.15     at /app/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:269:16
#0 25.15     at /app/node_modules/loader-fs-cache/index.js:139:9
#0 25.15     at /app/node_modules/graceful-fs/graceful-fs.js:61:14
#0 25.15     at FSReqCallback.oncomplete (node:fs:197:23) {
#0 25.15   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#0 25.15   library: 'digital envelope routines',
#0 25.15   reason: 'unsupported',
#0 25.15   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#0 25.15 }
#0 25.15
#0 25.15 Node.js v18.12.1
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1

```

**Comment by dodancs** [comment]
Hello Neodyn,

Thank you for submitting this issue. It is now fixed in the latest commit ab25c69.

For anyone getting the following issue after this fix:

```
#0 0.208 node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

please **update the Docker images before proceeding to build the containers**:

```bash
docker-compose -f docker/docker-compose.yml pull # update Docker images
docker-compose -f docker/docker-compose.yml up --build # build from source code
```
