### ISSUE TITLE
Assess: Group actions on news items cause exception in core backend

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#12]
Any group action, e.g. marking items as read (calling PUT http://localhost:5000/api/v1/assess/news-item-aggregates-group-action) causes this exception:
```
core_1        | [2021-10-31 22:17:16 +0000] [9] [ERROR] Error handling request /api/v1/assess/news-item-aggregates-group-action
core_1        | Traceback (most recent call last):
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
core_1        |     self.handle_request(listener_name, req, client, addr)
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
core_1        |     super().handle_request(listener_name, req, sock, addr)
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
core_1        |     respiter = self.wsgi(environ, resp.start_response)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
core_1        |     return self.wsgi_app(environ, start_response)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
core_1        |     response = self.handle_exception(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
core_1        |     return original_handler(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
core_1        |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
core_1        |     reraise(exc_type, exc_value, tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
core_1        |     raise value.with_traceback(tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
core_1        |     response = self.full_dispatch_request()
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
core_1        |     rv = self.handle_user_exception(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
core_1        |     return original_handler(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
core_1        |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
core_1        |     reraise(exc_type, exc_value, tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
core_1        |     raise value.with_traceback(tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
core_1        |     rv = self.dispatch_request()
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
core_1        |     return self.view_functions[rule.endpoint](**req.view_args)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
core_1        |     resp = resource(*args, **kwargs)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
core_1        |     return self.dispatch_request(*args, **kwargs)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
core_1        |     resp = meth(*args, **kwargs)
core_1        |   File "/app/taranis-ng-core/managers/auth_manager.py", line 142, in wrapper
core_1        |     return fn(*args, **kwargs)
core_1        |   File "/app/taranis-ng-core/api/assess.py", line 120, in put
core_1        |     if request.json['type'] == 'delete':
core_1        | KeyError: 'type'
```

In this particular example the request body was:
```
{
  "group": "4a107934-2c32-47df-815b-71cc8e972fbd",
  "action": "READ",
  "items": [
    {
      "type": "AGGREGATE",
      "id": 65
    },
    {
      "type": "AGGREGATE",
      "id": 64
    }
  ]
}
```
So there is a type, but inside the items.

**Comment by milankowww** [comment]
This should be fixed in [v21.10.6](https://github.com/SK-CERT/Taranis-NG/releases/tag/v21.10.6). Closing the ticket.
