### ISSUE TITLE
Assess: Filtering for this week raises exception

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#73]
```
core_1        | [2022-02-04 18:36:07 +0000] [409180] [ERROR] Error handling request /api/v1/assess/news-item-aggregates-by-group/963f0229-b9a4-4e40-82bd-e6ac068893a2?search=&read=true&important=false&relevant=false&in_analyze=false&range=WEEK&sort=DATE_ASC&offset=0&limit=20
core_1        | Traceback (most recent call last):
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
core_1        |     self.handle_request(listener_name, req, client, addr)
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
core_1        |     super().handle_request(listener_name, req, sock, addr)
core_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
core_1        |     respiter = self.wsgi(environ, resp.start_response)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
core_1        |     return self.wsgi_app(environ, start_response)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
core_1        |     response = self.handle_exception(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
core_1        |     return original_handler(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
core_1        |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
core_1        |     reraise(exc_type, exc_value, tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
core_1        |     raise value.with_traceback(tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
core_1        |     response = self.full_dispatch_request()
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
core_1        |     rv = self.handle_user_exception(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
core_1        |     return original_handler(e)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
core_1        |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
core_1        |     reraise(exc_type, exc_value, tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
core_1        |     raise value.with_traceback(tb)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
core_1        |     rv = self.dispatch_request()
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
core_1        |     return self.view_functions[rule.endpoint](**req.view_args)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
core_1        |     resp = resource(*args, **kwargs)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
core_1        |     return self.dispatch_request(*args, **kwargs)
core_1        |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
core_1        |     resp = meth(*args, **kwargs)
core_1        |   File "/app/managers/auth_manager.py", line 183, in wrapper
core_1        |     return fn(*args, **kwargs)
core_1        |   File "/app/api/assess.py", line 68, in get
core_1        |     return news_item.NewsItemAggregate.get_by_group_json(group_id, filter, offset, limit, user)
core_1        |   File "/app/model/news_item.py", line 480, in get_by_group_json
core_1        |     news_item_aggregates, count = cls.get_by_group(group_id, filter, offset, limit, user)
core_1        |   File "/app/model/news_item.py", line 456, in get_by_group
core_1        |     microsecond=0)
core_1        | ValueError: day is out of range for month
```

**Comment by dodancs** [comment]
Thank you for the submission. The filter was not coded properly but is now fixed.
